extra_css:
  - https://comping-style.qihang-zhang.com/stylesheets/extra.css
  
extra:
  homepage: https://qihang-zhang.com/
  categories:
    HTML5: html
    JavaScript: js
    CSS: css

markdown_extensions:
  attr_list: {}
  admonition: {}
  pymdownx.arithmatex:
      generic: true  
  toc:
    permalink: true
    toc_depth: 4
  md_in_html: {}
  pymdownx.highlight: {}
  footnotes: {}
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://comping-style.qihang-zhang.com/javascript/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

plugins:      
  search: {}
  bibtex:
    bib_file: 'docs/assets/references.bib'
  meta: {}
  tags:
    tags_file: tags.md          
    tags_allowed: []             
    tags_hierarchy: true
    tags_hierarchy_separator: /
    tags_sort_by: !!python/name:material.plugins.tags.tag_name
    tags_sort_reverse: false     
    tags_name_property: tags     
    tags_name_variable: tags
  info:
    enabled: false
    enabled_on_serve: true
    archive: false
    archive_stop_on_violation: false
  offline: {}
  blog:
    blog_dir: .
    authors_file: assets/.authors.yml
    blog_toc: true
    draft: false
    draft_if_future_date: true
    draft_on_serve: true
    post_date_format: medium
    post_dir: '{blog}/posts/'
    post_url_date_format: yyyy/MM/dd
    post_url_format: '{date}/{slug}'
    categories: true
    categories_name: Categories
    categories_url_format: 'category/{slug}'
    categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
    categories_allowed: []
  callouts: {}
  awesome-nav: {}

draft_docs: |
  drafts/
  private/
  *_wip.md
  !/keep_this.md

theme:
  name: material
  custom_dir: overrides
  features:
    - katex
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - toc.integrate
    - navigation.sections
    - content.code.copy
  language: en
  logo: https://comping-style.qihang-zhang.com/assets/fruit/watermelon.svg
  favicon: https://comping-style.qihang-zhang.com/assets/fruit/lemon.svg
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3


  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

dev_addr: 127.0.0.1:9000
