# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout edge repo
      - name: Checkout Edge Repo (self)
        uses: actions/checkout@v4

      # step 2: checkout core repo
      - name: Checkout Central Logic Repo
        uses: actions/checkout@v4
        with:
          repository: 'Qihang-Zhang/fused_mkdocs' # your core repo name
          ref: 'main' # suggest to point to a stable tag, like v1.0.0, to avoid being broken by future commits
          path: './fused_mkdocs' # download the core repo logic to this subdirectory
      
      - name: initialize the blog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          bash ./fused_mkdocs/maintain_config/copy_config.sh

      - name: install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH      

      - name: release the blog
        run: |
          uv run bash ./fused_mkdocs/mkdocs_publish.sh